### ISSUE TITLE
Running from SVG file possible

### ISSUE THREAD

**Issue by ghost** [dnfield/flutter_built_path#1]
Thanks for making this. It's a huge time saver.
But I looked at the demo and the SVG was inline and it would be great to be able to reference a folder of SVG files as part of the code gen.

Do you think it's also useful ?

**Comment by dnfield** [comment]
I'd like to do a full SVG preprocessor.  I'm not sure how that would look for just paths though - SVG paths have some attributes that go beyond a flutter path and it think it'd be confusing/limited.

What format would you have in mind?

**Comment by ghost** [comment]
Ah I did not realise that during the conversion process some information is
lost. Assuming I u deratand what you said.

  I have only used very simple SVG examples in my testing.

I also don't understand what you mean by format

Can you explain a bit more.

**Comment by dnfield** [comment]
So the scope of this package is just parsing SVG path data strings and fill rules into a Flutter `Path`.

A full fledged SVG path can also have fill properties (colors, opacities, gradients), stroke properties, and a bunch of other stuff.  Handling that properly is much more complicated than what this can do so far.

I have it in mind to implement a similar package for full fledged SVGs (supporting everything `flutter_svg` supports), but that's a bit more work and will probably require some refactoring of `flutter_svg` first.  It will also use some parts of this project's code.

With all of that said, it would be possible to have this package pull path data strings from a separate file instead of inline with the attribute, e.g. something like

```dart
@SvgPathFile('paths.json')
List<Path> get paths => _$paths;
```

And maybe that file would look something like
```json
[
  "M 0 0 ... z",
  "...",
  "..."
]
```

But I'm not sure if that's really any more useful (and I'd hestitate to use `.svg` because it would cause a lot of confusion about what is and isn't supported).

I'm thinking you might be looking for full SVG support, but I'm open to other ideas.

**Comment by ghost** [comment]
hey. thanks for explaining. It all makes sense now.

Yeah guilty as charged :) i am looking for full SVG and loading over the
network using cached image flutter plugin.

SO with that said, it sounds like this issue should be put on the
backburner OR just use a ".paths" file extension to load up what the system
supports for now.

Either is fine for me as i can use raster images for now for complex svgs
and load them at higher than needed resolution, so dont sweat it.

**Comment by dnfield** [comment]
Ok.  I'll close this, as I already have an issue open to track SVG codegen support: https://github.com/dnfield/flutter_svg/issues/38
